### ISSUE TITLE
Windows installation path

### ISSUE THREAD

**Issue by hombit** [matwey/fips3#115]
For now Windows installer put the application to `C:\Program Files\Fips-3.a.b`. I think, that user predicts that new program installation will rewrite old one. Should we change the path to `C:\Program Files\Fips-3`? This will prevent corruption of user's scripts and aliases after update.

**Comment by matwey** [comment]
We need to consult with @ForNeVeR to ensure that installer is able to correctly detect installed application and do upgrade.

**Comment by matwey** [comment]
By the way, how are automatic updates usually handled in Windows world?

**Comment by ForNeVeR** [comment]
There is essentially no single way. There're some install systems involving various online repositories (Chocolatey, Windows Store) and some self-checking systems (e.g. Squirrel), but none of them is widespread enough.

Probably Windows Store is the way to go, but you need to support older Windows systems, so we cannot use it. I wouldn't recommend to mess with "auto" update systems if you don't have to.
