### ISSUE TITLE
Prepare RPM packages

### ISSUE THREAD

**Issue by matwey** [matwey/fips3#12]
- [x] write `.desktop` file as per specs: https://standards.freedesktop.org/desktop-entry-spec/latest/
- [x] obtain scalable icon file: https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#directory_layout
- [x] modify `CMakeLists.txt` to install `.desktop` and icon. `$XDG_DATA_DIRS/applications` and `$XDG_DATA_DIRS/icons/hicolor/scalable/apps/`
- [x] write `README.md` file
- [x] write `.spec` file for RPM

**Comment by hombit** [comment]
Can we close it now?
