### ISSUE TITLE
Qt 5.12: blank window on macOS

### ISSUE THREAD

**Issue by hombit** [matwey/fips3#125]
Brand new Qt 5.12 produces app with blank window. All menus works, window initial geometry depends on image geometry. The bug exists for all `BITPIX` values, both for `master` branch and `3.3.0` tag. Everything works fine with Qt 5.11.2

MacOS 10.14.1, Apple Clang 10.0.0.

<img width="800" alt="screenshot 2018-12-07 at 10 26 34" src="https://user-images.githubusercontent.com/1784493/49633586-ebf32e80-fa0a-11e8-847c-78feaa0ba900.png">

**Comment by hombit** [comment]
Image appears after resize, but resize itself is very laggy

https://youtu.be/cJ7X6J36m2c

**Comment by hombit** [comment]
Related bugs: [QTBUG-72387](https://bugreports.qt.io/browse/QTBUG-72387?focusedCommentId=438022&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-438022), [QTBUG-71988](https://bugreports.qt.io/browse/QTBUG-71988)

**Comment by hombit** [comment]
Bug [was fixed in Qt 5.12.1](https://bugreports.qt.io/browse/QTBUG-71988), now it is [available in Homebrew](https://github.com/Homebrew/homebrew-core/commit/bc03ca8ad8f74be348801c99b78905926d91abc1) and now everything should work well. We should change [this part](https://github.com/matwey/fips3/commit/3fd9596aba99cb6ad03b7808b2cebc95f814275e#diff-af3b638bc2a3e6c650974192a53c7291R38) of `CMakeLists.txt` now.

**Comment by matwey** [comment]
Do I understand correctly, that I should revert 3fd9596aba99cb6ad03b7808b2cebc95f814275e?
