### ISSUE TITLE
Appveyor release deploy failed

### ISSUE THREAD

**Issue by matwey** [matwey/fips3#157]
Currently, I see the following in Appveyor CI:

```
Uploading artifacts...
[1/1] Fips-3.4.0-win64.msi (22,282,240 bytes)...100%
Deploying using GitHub provider
Creating "3.4.0" release for repository "matwey/fips3" tag "3.4.0" commit "f68ca188b55d0f339f4849f10c38c2d65f3d11c1"...Error creating GitHub release: Error reading repository 'matwey/fips3' releases: 401 - Unauthorized
```

Probably, the keys or tokens are expired for some reason.

**Comment by ForNeVeR** [comment]
FYI, to publish a release, you should create a GitHub access token with release access, and then encrypt it via [this Appveyor page](https://ci.appveyor.com/tools/encrypt).
