### ISSUE TITLE
Implement OpenGL 3.x plans

### ISSUE THREAD

**Issue by matwey** [matwey/fips3#84]
Hello, @hombit 

Could you please try to use `feature/openglplanfactory` to implement OpenGL 3.x based plans. This is to check that overall plan architecture is scaled well enough.

- [ ] Ask for 3.0 version in `OpenGLWidget` constructor
- [ ] Implement appropriate `*OpenGLTexture` counterparts (see `opengltexture.cpp`)
- [ ] Implement appropriate `*OpenGLPlan*` counterparts (see `openglplan.cpp`)
- [ ] Add newly added `*OpenGLPlan*` to OpenGLPlanFactory (prepending them in `resolveOpenGLPlan` like the following: 
```
AbstractOpenGLPlan* OpenGLPlanFactory::operator() (const FITS::HeaderDataUnit<FITS::DataUnit<qint16>>& hdu) const {
        return resolveOpenGLPlan<Int16OpenGL3xPlan, Int16OpenGLPlan>(features_, hdu);
}
```

**Comment by hombit** [comment]
Done for OpenGL 3.3 in #104
